;Custom_OpenClash_Rules
;全分组防 DNS 泄漏订阅转换模板
;作者：https://github.com/Aethersailor
;项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules
;基于 ACL4SSR 模板魔改而来，感谢原作者！
;<建议>搭配本项目配套设置，实现最佳化的 OpenClash 使用效果！
;设置方案：https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88

[custom]
;设置规则标志位
;以下规则，按照从上往下的顺序遍历，优先命中上位规则，规则重复无影响
;修改顺序会影响分流效果
ruleset=🚀 手动选择,[]GEOSITE,gfw
ruleset=🚀 手动选择,[]GEOIP,telegram,no-resolve
ruleset=🚀 手动选择,[]GEOIP,facebook,no-resolve
ruleset=🚀 手动选择,[]GEOIP,twitter,no-resolve
ruleset=🎯 全球直连,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
custom_proxy_group=🚀 手动选择`select`[]♻️ 自动选择`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🎯 全球直连`select`[]DIRECT
;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true

