version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:40"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 20
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "automerge"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      codeql-action:
        patterns:
          - "github/codeql-action/*"
      routine-updates:
        patterns:
          - "*"
        exclude-patterns:
          - "github/codeql-action/*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:50"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "automerge"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      routine-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"
