[custom]
;设置规则标志位
;以下规则，按照从上往下的顺序遍历，优先命中上位规则，规则重复无影响
;修改顺序会影响分流效果
ruleset=🚀 手动选择,[]GEOSITE,gfw
ruleset=🚀 手动选择,[]GEOIP,telegram,no-resolve
ruleset=🚀 手动选择,[]GEOIP,facebook,no-resolve
ruleset=🚀 手动选择,[]GEOIP,twitter,no-resolve
ruleset=🎯 全球直连,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
;节点地区分组参考本项目推荐机场而设立
custom_proxy_group=🚀 手动选择`select`[]♻️ 自动智能`.*
custom_proxy_group=♻️ 自动智能`smart`.*`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions
custom_proxy_group=🎯 全球直连`select`[]DIRECT
;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true

