[General]
# 先安装本目录 local/ 中的共享组件，再启用模块。
# dnsmasq-rules-source: adblockfilters-dnsmasq
# dnsmasq-rules-url: https://gcore.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockdnsmasq.txt
ENABLE_REDIRECT_DNS = 1
