name: 国内冷门域名上报
description: 上报你发现的认为应当直连的国内域名
title: '[国内域名上报]'
labels: 'enhancement'

body:
  - type: checkboxes
    id: verify_steps
    attributes:
      label: Verify Steps
      description: |
        在提交之前，请确认：
      options:
        - label: 我知晓大部分国内域名已经包含在 GeoSite 中，并且可以实现绕过内核访问
          required: true
        - label: 我确认该域名被解析为 Fake-IP
          required: true
        - label: 我确认域名进入内核，且未能命中任何规则且错误分流至漏网之鱼策略组中
          required: true
        - label: 我确认该域名的解析结果指向中国大陆 IP 地址
          required: true

  - type: textarea
    id: cn_domain
    attributes:
      label: 需要添加的国内域名
      description: |
        列出需要添加的国内域名
    validations:
      required: true

  - type: textarea
    id: describe_domain
    attributes:
      label: 简单描述该域名
      description: |
        对域名用途清晰而简洁的描述
    validations:
      required: true

