name: IPv6 设置方案错判上报
description: 上报你在 IPv6 设置方案中发现的问题
title: '[IPv6 设置方案错误]'
labels: 'documentation'

body:
  - type: checkboxes
    id: verify_steps
    attributes:
      label: Verify Steps
      description: |
        在提交之前，请确认：
      options:
        - label: 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
          required: true
        - label: 我已经尝试通过观察日志、观察面板、检查 dns 解析流程等方式自行排查故障
          required: true
        - label: 我使用的是 OpenWrt/ImmortalWrt 官方发布固件或官方 ImageBuilder 生成的固件，非第三方编译版本
          required: true
        - label: 我部署的是主路由网络架构，而非旁路由
          required: true
        - label: 我确认我的运营商提供了 IPv6-PD 地址
          required: true
        - label: 我确认我使用的节点支持 IPv6 出站
          required: true
        - label: 我确认我已经完全按照 Wiki 中的设置方案进行了设置
          required: true
        - label: 我确认我遇到的现象是设置方案的问题导致的
          required: true
        - label: 我知晓开发者已经完全检查过设置方案的可用性
          required: true
        - label: 我有能力协助开发并解决此问题
          required: false
        - label: 我提交的**是无意义的**质疑或提问
          required: false

  - type: textarea
    id: describe_bug
    attributes:
      label: 描述 IPv6 设置方案存在的问题
      description: |
        对问题本身清晰而简洁的描述
    validations:
      required: true

  - type: textarea
    id: describe_phenomenon
    attributes:
      label: 描述设置方案问题导致的故障现象
      description: |
        对故障现象清晰而简洁的描述
    validations:
      required: true

  - type: textarea
    id: describe_solution
    attributes:
      label: 我提供的解决方案
      description: |
        提供你认为可行的解决方案
    validations:
      required: true

