name: 模板错判上报
description: 上报你在模板中发现的 BUG
title: '[模板错误]'
labels: 'bug'

body:
  - type: checkboxes
    id: verify_steps
    attributes:
      label: Verify Steps
      description: |
        在提交之前，请确认：
      options:
        - label: 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
          required: true
        - label: 我已经尝试通过观察日志、观察面板、检查 dns 解析流程等方式自行排查故障
          required: true
        - label: 我知晓订阅转换模板只是一个订阅转换后端使用的模板，具有普适性
          required: true
        - label: 我知晓本项目提供订阅转换模板，只影响分流
          required: true
        - label: 我知晓本项目订阅转换模板引用的是第三方上游规则，其是否更新与本项目无关
          required: true
        - label: 我知晓本项目有非常多的用户，而我的问题很有可能是个例
          required: true
        - label: 我使用的是 OpenWrt/ImmortalWrt 官方发布的固件或官方 ImageBuilder 生成的固件，非第三方编译版本
          required: true
        - label: 我部署的是主路由网络架构，而非旁路由
          required: true
        - label: 我使用的是最新的 dev 版本 OpenClash 和内核
          required: true
        - label: 我已经完全按照 Wiki 中的方案对 OpenClash 进行设置
          required: true
        - label: 我已经完全阅读了 Wiki 中的[故障排除](https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4)章节
          required: true
        - label: 我确认这确实是本项目模板文件导致的问题
          required: true
        - label: 我已经尝试换用本项目提供的订阅转换后端服务
          required: true
        - label: 我有能力协助开发并解决此问题
          required: false
        - label: 我提交的**是无意义的**质疑或提问
          required: false

  - type: input
    id: openclash_version
    attributes:
      label: OpenClash Version
      description: |
        OpenClash 版本号
      placeholder: "v0.0.0-beta"
    validations:
      required: true

  - type: dropdown
    id: bug_ini
    attributes:
      label: 存在问题的模板文件
      description: |
        发现问题所在的模板
      multiple: true
      options:
        - Custom_Clash.ini
        - Custom_Clash_Full.ini
        - Custom_Clash_GFW.ini
        - Custom_Clash_Lite.ini
        - Custom_Clash_Mainland.ini
    validations:
      required: true    

  - type: textarea
    id: describe_bug
    attributes:
      label: 描述模板存在的 BUG
      description: |
        对 Bug 本身清晰而简洁的描述
    validations:
      required: true

  - type: textarea
    id: describe_phenomenon
    attributes:
      label: 描述模板 BUG 导致的故障现象
      description: |
        对故障现象清晰而简洁的描述
    validations:
      required: true

  - type: textarea
    id: describe_solution
    attributes:
      label: 我提供的解决方案
      description: |
        提供你认为可行的解决方案
    validations:
      required: true


