[General]
# Custom_OpenClash_Rules
# OpenClash 远程 YAML 覆写模块（标准版）
# 对应配置：cfg/yaml/Custom_Clash.yaml
# 模块变量：EN_KEY1=节点订阅链接

DOWNLOAD_FILE = url=https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@refs/heads/main/cfg/yaml/Custom_Clash.yaml, path=/etc/openclash/config/Custom_Clash.yaml, force=true
CONFIG_FILE = /etc/openclash/config/Custom_Clash.yaml
SUB_INFO_URL = $EN_KEY1
RESTART = true

[Overwrite]
ruby_map_edit "$CONFIG_FILE" "['proxy-providers']" "provider1" "['url']" "$EN_KEY1"
