name: Update Custom_Clash_Mainland.ini

on:
  push:
    paths:
      - cfg/Custom_Clash.ini

jobs:
  update-mainland:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate Custom_Clash_Mainland.ini
      run: python py/generate_mainland.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add cfg/Custom_Clash_Mainland.ini
        git commit -m "Update Custom_Clash_Mainland.ini based on Custom_Clash.ini"
        git push origin HEAD
